language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t smolique/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true smolique/react-test npm test

after_success:
  - docker build -t smolique/multi-client ./client
  - docker build -t smolique/multi-nginx ./nginx
  - docker build -t smolique/multi-server ./server
  - docker build -t smolique/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push smolique/multi-client
  - docker push smolique/multi-nginx
  - docker push smolique/multi-server
  - docker push smolique/multi-worker
